# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "sr.cn.buildpacks.geo"
version = "0.0.1"
name = "geo Cloud Native Buildpack"

# Stacks that the buildpack will work with
[[stacks]]
id = "heroku-20"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
